spring.application.name=seo2yeon_t_Backend

# Server
server.port=8080
server.servlet.context-path=/api

# Database (PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ???
neis.api.url=https://open.neis.go.kr/hub/schoolInfo
neis.api.key=${NEIS_API_KEY}
